const sharedItems = [
    "Ayesti",
    "Aungty",
    "Baju",
    "Bala",
    "Bangle",
    "Bicha",
    "Bracelet",
    "Buttam",
    "Bati",
    "Bauti",
    "Chain",
    "Chik",
    "Chur",
    "Churi",
    "Chamus",
    "Chandi-Rupa",
    "Center piss",
    "Court pin",
    "Dul",
    "Earring pair",
    "Ghaar tana pair",
    "Glass",
    "Gold",
    "Haar",
    "Hair chain pair",
    "Hath panja",
    "Jhapta",
    "Jumka pair",
    "Kaan tana pair",
    "Kankon",
    "Konhkon",
    "Key",
    "Kontho chik",
    "Locket",
    "Locket & chain",
    "Mangalsutra",
    "Mantasha",
    "Medal",
    "Madli",
    "Mukut",
    "Necklace",
    "Nose pin",
    "Noth",
    "Nupur",
    "Pasha pair",
    "Payel",
    "Pola",
    "Plate",
    "Ring",
    "Ball ring",
    "Ratan chur",
    "Shakha",
    "Side clip",
    "Sita haar",
    "Sithi patti",
    "Silver",
    "Spcial item",
    "Shakha piss",
    "Sui suta",
    "Tikly",
    "Taj",
    "Tabic,",
    "Tip",
    "Zoroa haar"
];

module.exports = {
    hallmark: sharedItems,
    xray: sharedItems
};

